# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dreamer4',
                'doc_host': 'https://dirkmcpherson.github.io',
                'git_url': 'https://github.com/dirkmcpherson/dreamer4',
                'lib_path': 'dreamer4'},
  'syms': {'dreamer4.dreamer4': {}, 'dreamer4.envs.pinpad': {}, 'dreamer4.mocks': {}, 'dreamer4.trainers': {}}}
