# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tokenizer.ipynb.

# %% auto 0
__all__ = ['show_reconstructions', 'debug_latents_and_errors', 'SimpleConvTokenizer']

# %% ../nbs/01_tokenizer.ipynb 2
import torch
from ._core import *
import matplotlib.pyplot as plt

# %% ../nbs/01_tokenizer.ipynb 3
from . import VideoTokenizer

@torch.no_grad()
def show_reconstructions(
    model: VideoTokenizer,
    video: torch.Tensor,
    title_prefix: str = "",
    max_time: int = 4,
):
    """
    Show original vs reconstruction for a single video batch element.
    """
    device = next(model.parameters()).device
    model.eval()

    video = batchify_video(video)
    video = video.to(device)

    recon = model.decode(
        model.tokenize(video),
        height=video.shape[-2],
        width=video.shape[-1],
    )

    video = video[0].cpu()   # (c, t, h, w)
    recon = recon[0].cpu()

    c, t, h, w = video.shape
    t_show = min(t, max_time)

    fig, axes = plt.subplots(2, t_show, figsize=(3 * t_show, 6))

    for i in range(t_show):
        axes[0, i].imshow(video[:, i].permute(1, 2, 0).clamp(0, 1))
        axes[0, i].set_title(f"{title_prefix}orig t={i}")
        axes[0, i].axis("off")

        axes[1, i].imshow(recon[:, i].permute(1, 2, 0).clamp(0, 1))
        axes[1, i].set_title(f"{title_prefix}recon t={i}")
        axes[1, i].axis("off")

    plt.tight_layout()
    plt.show()


# %% ../nbs/01_tokenizer.ipynb 7
import math
import torch.nn.functional as F


@torch.no_grad()
def debug_latents_and_errors(
    model: VideoTokenizer,
    video: torch.Tensor,
    patch_size: int | None = None,
    frame_index: int = 0,
):
    """
    - Prints latent norm/variance stats.
    - Shows pixel-wise error and patch-wise error heatmaps for one frame.
    """

    model.eval()
    video = batchify_video(video).to(model.device)      # (b,c,t,h,w)
    b, c, t, h, w = video.shape
    patch_size = patch_size or model.patch_size

    # --- latents ---
    latents = model.tokenize(video)                     # (b,t,n,d_latent)
    b, t, n, d_latent = latents.shape

    lat_mean = latents.mean(dim=(0,1,2))
    lat_std  = latents.std(dim=(0,1,2))
    lat_norm = latents.norm(dim=-1)                    # (b,t,n)

    print("latents shape:", latents.shape)
    print("latent dim:", d_latent, "num_latent_tokens:", n)
    print("latent per-dim mean (first 5):", lat_mean[:5].cpu().numpy())
    print("latent per-dim std  (first 5):", lat_std[:5].cpu().numpy())
    print("latent L2 norm stats: mean={:.3f}, std={:.3f}, min={:.3f}, max={:.3f}".format(
        lat_norm.mean().item(), lat_norm.std().item(),
        lat_norm.min().item(), lat_norm.max().item()
    ))

    # histogram of latent norms
    plt.figure(figsize=(4,3))
    plt.hist(lat_norm.flatten().cpu().numpy(), bins=40)
    plt.title("latent L2 norms")
    plt.xlabel("norm"); plt.ylabel("count")
    plt.tight_layout()
    plt.show()

    # --- reconstruction + error ---
    recon = model.decode(latents, height=h, width=w)
    recon = recon.clamp(0, 1)

    mse = F.mse_loss(video, recon).item()
    print("global MSE:", mse)

    vid0 = video[0, :, frame_index].cpu()              # (c,h,w)
    rec0 = recon[0, :, frame_index].cpu()

    err = (vid0 - rec0).pow(2).mean(dim=0)             # (h,w) per-pixel MSE

    # patch-wise error (mean over patch)
    ph, pw = h // patch_size, w // patch_size
    err_patch = err.view(ph, patch_size, pw, patch_size).mean(dim=(1,3))  # (ph,pw)

    # --- plots ---
    fig, axes = plt.subplots(1, 3, figsize=(12,4))

    axes[0].imshow(vid0.permute(1,2,0))
    axes[0].set_title("orig frame t={}".format(frame_index))
    axes[0].axis("off")

    axes[1].imshow(rec0.permute(1,2,0))
    axes[1].set_title("recon frame t={}".format(frame_index))
    axes[1].axis("off")

    im = axes[2].imshow(err, cmap="viridis")
    axes[2].set_title("per-pixel error")
    axes[2].axis("off")
    fig.colorbar(im, ax=axes[2])
    plt.tight_layout()
    plt.show()

    # patch error heatmap
    plt.figure(figsize=(4,4))
    plt.imshow(err_patch, cmap="magma")
    plt.title("per-patch error")
    plt.colorbar()
    plt.axis("off")
    plt.tight_layout()
    plt.show()

    return latents.cpu(), vid0, rec0, err, err_patch


# %% ../nbs/01_tokenizer.ipynb 12
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from einops import rearrange
import matplotlib.pyplot as plt
import numpy as np
from torch.optim import AdamW

class SimpleConvTokenizer(nn.Module):
    def __init__(
        self,
        image_channels=3,
        dim=64,                # Base channel width
        dim_latent=256,        # Final token vector size
        down_steps=4,          # 64px -> 4px grid (16 tokens total)
        image_size=64,
    ):
        super().__init__()
        self.dim_latent = dim_latent
        self.down_steps = down_steps
        self.image_size = image_size

        # Calc the token count for the dynamics model
        self.grid_h = image_size // (2 ** down_steps)
        self.grid_w = image_size // (2 ** down_steps)
        self.num_latent_tokens = self.grid_h * self.grid_w
        
        # --- Encoder ---
        layers = []
        c_in = image_channels
        c_out = dim
        
        for _ in range(down_steps):
            layers.extend([
                nn.Conv2d(c_in, c_out, kernel_size=4, stride=2, padding=1),
                nn.ReLU(),
                nn.GroupNorm(8, c_out) 
            ])
            c_in = c_out
            c_out = c_out * 2
            
        self.encoder = nn.Sequential(*layers)
        
        # Latent Projection
        self.to_latent = nn.Linear(c_in, dim_latent)

        self.latent_norm = nn.LayerNorm(dim_latent)

        # --- Decoder ---
        self.from_latent = nn.Linear(dim_latent, c_in)
        
        dec_layers = []
        c_out = c_in // 2
        
        for _ in range(down_steps - 1):
            dec_layers.extend([
                nn.ConvTranspose2d(c_in, c_out, kernel_size=4, stride=2, padding=1),
                nn.ReLU(),
                nn.GroupNorm(8, c_out)
            ])
            c_in = c_out
            c_out = c_out // 2
            
        dec_layers.append(
            nn.ConvTranspose2d(c_in, image_channels, kernel_size=4, stride=2, padding=1)
        )
        self.decoder = nn.Sequential(*dec_layers)
        
        self.device_param = nn.Parameter(torch.empty(0))

    @property
    def device(self):
        return self.device_param.device

    def encode(self, video):
        # Input: (B, C, T, H, W)
        b, c, t, h, w = video.shape

        assert h == self.image_size and w == self.image_size


        x = rearrange(video, 'b c t h w -> (b t) c h w')
        
        x = self.encoder(x) # -> (BT, C_final, H', W')
        
        # Flatten spatial grid to tokens
        x = rearrange(x, 'bt c h w -> bt (h w) c')
        
        latents = self.to_latent(x)
        latents = self.latent_norm(latents)
        latents = rearrange(latents, '(b t) n d -> b t n d', b=b, t=t)
        return latents

    def decode(self, latents, height=64, width=64):
        # Input: (B, T, N, D)
        b, t, n, d = latents.shape
        x = rearrange(latents, 'b t n d -> (b t) n d')
        
        x = self.from_latent(x)
        
        # Unflatten tokens back to grid
        grid_h = height // (2 ** self.down_steps)
        grid_w = width // (2 ** self.down_steps)
        x = rearrange(x, 'bt (h w) c -> bt c h w', h=grid_h, w=grid_w)
        
        x = self.decoder(x)
        video = rearrange(x, '(b t) c h w -> b c t h w', b=b, t=t)
        return video

    def forward(self, video, return_latents=False):
        latents = self.encode(video)
        if return_latents: return latents
        
        recon = self.decode(latents, height=video.shape[-2], width=video.shape[-1])
        loss = F.mse_loss(recon, video)
        return loss  # Trainer expects single scalar return
    
    @torch.no_grad()
    def tokenize(
        self,
        video
    ):
        self.eval()
        return self.forward(video, return_latents = True)
