# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_transformer.ipynb.

# %% auto 0
__all__ = ['device']

# %% ../nbs/02_transformer.ipynb 2
import torch
# from dreamer4._core import *
# from dreamer4._tokenizer import *
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from einops import rearrange, repeat, einsum
import matplotlib.pyplot as plt

# Check for CUDA/MPS
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Running on: {device}")
